public class Demo {
    public static void main(String[] args) {

        //Example 1 of exception handling ( ArithmeticException )
//        int a=10,b=0,c=0;
//        try {
//            c=a/b;
//        }
//        catch (ArithmeticException e)
//        {
//            System.out.println("exception is: "+e);
//        }
//        System.out.println(c);
//        System.out.println("end of main method");


        //Example 2 of exception handling ( NumberFormatException )
        //NumberFormatException occur when string cannot be converted to integer.

//        String str = "hi";
//        int a=0;
//        try {
//            a=Integer.parseInt(str);    //stm1
//        }
//        catch (NumberFormatException n)
//        {
//            System.out.println(n);  //stm2
//        }
//        System.out.println(a);  //stm3
//        System.out.println("main method end");  //stm4



        //use of try catch and finally block
//        int a=10,b=0,c=0;
//        try {
//            c=a/b;
//        }
//        catch (ArithmeticException e)
//        {
//            System.out.println("exception is: "+e);
//            System.out.println("exception occur due to divide by zero ");
//        }
//        finally {
//            System.out.println(c);
//            System.out.println("security related code and database dis-connectivity code handle");
//        }
//        System.out.println("end of main method");
    }
}

